############################# Task 16: Software Packages    #####################
### Create a playbook /home/automation/plays/packages.yml                     ###
### that runs on all inventory hosts and does the following:                  ###
## Installs tcpdump and mailx packages on hosts in the proxy host groups.     ###
## Installs lsof and mailx and packages on hosts in the database host groups. ###
#################################################################################

---
- name: Install Packages
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    proxy:
      - tcpdump
      - mailx

    database:
      - lsof
      - mailx 

  tasks:
    - name: install tcpdump and mailx on proxies
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ proxy }}"
      when: ansible_fqdn in groups['proxy']

    - name: Install lsof and mailx on database
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ database }}"
      when: ansible_fqdn in groups['database'] 
