- name: use template to create a server list
  hosts: database
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: create server list file
      template: 
        src: templates/server_list.j2
        dest: /etc/server_list.txt
        mode: 0600
        setype: net_conf_t

